using FamilienKochbuch.Domain.Common;

namespace FamilienKochbuch.Domain.MealPlanning;

/// <summary>
/// Aggregated shopping list for a single <see cref="MealPlan"/> (P3-5).
/// One row per MealPlan — the 1:1 relationship is enforced by a unique
/// index on <see cref="MealPlanId"/>. Items live in <see cref="Items"/>
/// and are generated by <c>ShoppingListGenerator</c> from the plan's
/// non-leftover slots; user-added items ("Manual" source) survive
/// regenerates so the user never loses a typed-in entry when the
/// aggregator re-runs.
///
/// OFF3: implements <see cref="IVersionedEntity"/> so every add /
/// regenerate / touch bumps a monotonically increasing
/// <see cref="Version"/> used as the ETag payload + <c>If-Match</c>
/// concurrency token on mutation endpoints.
/// </summary>
public sealed class ShoppingList : IVersionedEntity
{
    // EF-friendly parameterless ctor.
    private ShoppingList() { }

    public ShoppingList(Guid mealPlanId, DateTimeOffset createdAt)
    {
        if (mealPlanId == Guid.Empty)
            throw new ArgumentException("MealPlanId must not be empty.", nameof(mealPlanId));

        Id = Guid.NewGuid();
        MealPlanId = mealPlanId;
        Version = 0;
        CreatedAt = createdAt;
        UpdatedAt = createdAt;
        LastGeneratedAt = createdAt;
    }

    public Guid Id { get; private set; }
    public Guid MealPlanId { get; private set; }
    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset UpdatedAt { get; private set; }

    /// <summary>
    /// OFF3 optimistic-concurrency token. Bumped whenever the list's
    /// user-visible state changes (regenerate, manual add, edit, delete
    /// of items). Starts at 0 on a fresh list.
    /// </summary>
    public int Version { get; private set; }

    /// <summary>
    /// <see cref="IVersionedEntity.BumpVersion"/>. Every public mutation
    /// on the list invokes this exactly once per state change.
    /// </summary>
    public void BumpVersion() => Version++;

    /// <summary>
    /// Timestamp of the last aggregator run. Used by the carryover flow
    /// (plan §Carryover): "subsequent regenerates of the same week do
    /// NOT re-apply carryover merge" — the endpoint decides based on
    /// whether this timestamp is the same as <see cref="CreatedAt"/>.
    /// </summary>
    public DateTimeOffset LastGeneratedAt { get; private set; }

    public ICollection<ShoppingListItem> Items { get; private set; } = new List<ShoppingListItem>();

    /// <summary>Marks a fresh generator run; bumps the edit timestamps + <see cref="Version"/>.</summary>
    public void MarkRegenerated(DateTimeOffset at)
    {
        LastGeneratedAt = at;
        UpdatedAt = at;
        BumpVersion();
    }

    /// <summary>Bumps <see cref="UpdatedAt"/> + <see cref="Version"/> without resetting <see cref="LastGeneratedAt"/>.</summary>
    public void Touch(DateTimeOffset at)
    {
        UpdatedAt = at;
        BumpVersion();
    }
}
